-- Fix: la secuencia no avanzaba en UPDATE porque GENERATED ALWAYS solo asigna en INSERT.
-- Esto rompía el optimistic lock (WHERE sequence = lastKnown siempre coincidía)
-- y el watermark (trigger AFTER INSERT OR UPDATE veía NEW.sequence sin cambios).

-- Cambiar a GENERATED BY DEFAULT para que BEFORE UPDATE trigger pueda asignar
alter table sync_entities alter column sequence set generated by default;

-- Trigger BEFORE UPDATE que avanza la secuencia en cada UPDATE
create or replace function public.bump_entity_sequence()
returns trigger
language plpgsql
as $$
begin
  new.sequence := nextval(pg_get_serial_sequence(
    tg_table_schema || '.' || tg_table_name, 'sequence'
  ));
  return new;
end;
$$;

create trigger trg_bump_entity_sequence
  before update on public.sync_entities
  for each row
  execute function public.bump_entity_sequence();
